apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 8fa82c58a3d9889c75d86bd0317a4443440c2ca2
    app.quarkus.io/build-timestamp: 2022-07-04 - 15:57:10 +0000
  labels:
    app.kubernetes.io/name: hello-pvdf
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: hello-pvdf
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: hello-pvdf
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
