version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ruleops-ui"
    schedule:
      interval: "daily"
    # ignore "Development dependency group" e.g.: devDependencies 
    allow:
      - dependency-type: "production"
    # only require security updates and want to exclude version updates, ref https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates
    open-pull-requests-limit: 0
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    # only require security updates and want to exclude version updates, ref https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates
    open-pull-requests-limit: 0
