# Integration and End to End tests which runs locally using a Kubernetes (KinD) cluster
# to verify the RuleOps's functionality
name: Integration & End to End tests using KinD

on:
  push:
    branches: [ 'main' ]
    paths-ignore:
      - 'ruleops-ui/**'
  pull_request:
    branches: [ '*' ]
    paths-ignore:
      - 'ruleops-ui/**'

jobs:
  ruleops_e2etest_kind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Set up Java and Maven
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 17
          distribution: temurin
          cache: 'maven'

      - name: Kubernetes KinD Cluster
        uses: container-tools/kind-action@v2

      - name: Build RuleOps and perform E2E test
        run: mvn -B clean install --file pom.xml -Dquarkus.quinoa=false
